### ISSUE TITLE
404 http://www.researchobject.org/examples/parameter-optimization-of-an-ecological-niche-modeling-workflow-research-object/

### ISSUE THREAD

**Issue by gambl** [ResearchObject/researchobject.org#5]

**Comment by stain** [comment]
See http://purl.org/net/svm-opt-research-object and http://www.researchobject.org/example-of-encoding-an-ro-using-rdf-a/ -- not sure why http://www.researchobject.org/examples/parameter-optimization-of-an-ecological-niche-modeling-workflow-research-object/ should have worked? Where is it linked from? 

Closed as "Won't fix"
