### ISSUE TITLE
inconsistent co-author ordering on "Why Linked Data is not enough"

### ISSUE THREAD

**Issue by davidderoure** [ResearchObject/researchobject.org#6]
This point of accuracy in citation has been pointed out to me by a PhD student: the author ordering on the recommended citation on http://www.researchobject.org/publications/ is:

_Sean Bechhofer, John Ainsworth, Jitenkumar Bhagat, Iain Buchan, Phillip Couch, Don Cruickshank, Mark Delderfield, Ian Dunlop, Matthew Gamble, Carole Goble, Danius Michaelides, Paolo Missier, Stuart Owen, David Newman, David De Roure, Shoaib Sufi_

The ordering on the paper itself  (when you follow the DOI) is:

_Sean Bechhofer, Iain Buchan, David De Roure, Paolo Missier, John Ainsworth, Jiten Bhagat, Philip Couch, Don Cruickshank, Mark Delderfield, Ian Dunlop, Matthew Gamble, Danius Michaelides, Stuart Owen, David Newman, Shoaib Sufi, Carole Goble_

**Comment by stain** [comment]
My apologies - this might have happened as we got it confused with the older https://doi.org/10.1109/eScience.2010.21

I believe Catarina fixed this on our website back in March so I'll close this issue.
